auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         1
permalink:        /:categories/:year/:month/:day/:title/

title:            "Goochin"
url:              http://hi.imgoochin.com
feed:             /feed.xml
author:
    name:         Goochin
    twitter:      twitter.com/goochin
    key:          goochin
description:      "想活成什么摸样，与岁月无关~"
copyright:        "CopryRight Goochin 2013 by GitHub and Jekyll"
headdesc:         "另一个地方"
headkeys:         "设计,开发,思考,生活,豆瓣,读书,电影,音乐,游记"
